name: Invader Check

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  check_invaders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch website content
        id: fetch_content
        run: |
          content=$(curl -s https://www.space-invaders.com/world/)
          echo "web_content<<EOF" >> $GITHUB_OUTPUT
          echo "$content" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Extract invader count
        id: extract_count
        run: |
          web_content="${{ steps.fetch_content.outputs.web_content }}"
          
          # Pre-process the HTML: remove newlines, then squeeze multiple spaces into one
          # Focus on the part of HTML that contains the score
          score_section=$(echo "$web_content" | grep -o '<div class="score">.*Invaders.*</div>' || true)
          
          if [ -z "$score_section" ]; then
            echo "Score section not found in the HTML."
            invader_count="error_not_found"
          else
            # Remove newlines and carriage returns from the extracted section
            processed_score_section=$(echo "$score_section" | tr -d '\n\r')
            # Squeeze multiple spaces into single spaces
            processed_score_section=$(echo "$processed_score_section" | tr -s ' ')

            echo "Processed score section: $processed_score_section" # Debugging line

            # Attempt to extract the number using a robust sed command
            invader_text=$(echo "$processed_score_section" | sed -n 's/.*<div class="score"> *<span> *\([0-9,]*\) Invaders.*/\1/p')

            if [ -z "$invader_text" ]; then
              echo "Invader count not found with sed on processed section."
              # Fallback: try grep on the processed section (similar to original but on cleaned HTML)
              invader_text=$(echo "$processed_score_section" | grep -oP '<div class="score">\s*<span>\s*\K[0-9,]+(?=\s*Invaders)' || true)
              if [ -z "$invader_text" ]; then
                echo "Invader count not found with grep on processed section either."
                invader_count="error_not_found"
              else
                invader_count=$(echo "$invader_text" | sed 's/,//g')
              fi
            else
              invader_count=$(echo "$invader_text" | sed 's/,//g')
            fi
          fi
          
          echo "Final extracted invader count: $invader_count"
          echo "current_invaders=$invader_count" >> $GITHUB_OUTPUT

      - name: Read previous invader count
        id: read_previous_count
        run: |
          if [ -f invader_count.txt ]; then
            previous_invaders=$(cat invader_count.txt)
          else
            previous_invaders="0" # Default if file doesn't exist
          fi
          echo "Previous invader count: $previous_invaders"
          echo "previous_invaders=$previous_invaders" >> $GITHUB_OUTPUT

      - name: Compare counts and notify
        if: steps.extract_count.outputs.current_invaders != steps.read_previous_count.outputs.previous_invaders && steps.extract_count.outputs.current_invaders != 'error_not_found'
        run: |
          echo "Invader count has changed!"
          # Send notification only if current_invaders is a number
          curl -d "New invader count: ${{ steps.extract_count.outputs.current_invaders }}" ntfy.sh/invader_alert
          echo "${{ steps.extract_count.outputs.current_invaders }}" > invader_count.txt
          
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add invader_count.txt
          git commit -m "Update invader count to ${{ steps.extract_count.outputs.current_invaders }}" || echo "No changes to commit"
          git push || echo "No changes to push"
          
      - name: Counts are the same or count not found
        if: steps.extract_count.outputs.current_invaders == steps.read_previous_count.outputs.previous_invaders || steps.extract_count.outputs.current_invaders == 'error_not_found'
        run: |
          if [ "${{ steps.extract_count.outputs.current_invaders }}" == "error_not_found" ]; then
            echo "Could not extract current invader count. Previous count was ${{ steps.read_previous_count.outputs.previous_invaders }}."
          else
            echo "Invader count has not changed. Current count: ${{ steps.extract_count.outputs.current_invaders }}."
          fi
